
sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
branches:
  only:
    - master
before_install:
  - npm i -g npm@^3.0.0
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
