language: node_js

node_js:
  - "0.10"

before_script:
  - echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

branches:
  only:
    - master

notification:
  email:
    - zack9433@gmail.com
