language: node_js

node_js:
  - "0.10"

before_install:
  - echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

env:
  - secure: "Hrbf24uWbnTt8EMMhkTiAhJ0452rP9v3OpZ3w+YEljuNwQ4Ls6LusJkdckqSU+4XneXh3g5lq1rPlSQaSvXBPFxGu/IAsPhCr8EXkiqsyI6Qb1/QrwH3VrDjg/s4wNNpzlBPYOPXGbThcECFY1hEaXKLuGrwhYgHAF3cfuPheJM="

branches:
  only:
    - master

notification:
  email:
    - zack9433@gmail.com
