language: node_js

node_js:
  - "0.10"

before_install:
  - echo -n $travisci_{1..35} >> ~/.ssh/travis_key_base64
  - base64 --decode --ignore-garbage ~/.ssh/travis_key_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g bower
  - bower install

env:
  global:
    - secure: "lFVTGnPbx5CBNy/e2dd9bBIK92DfJ9LIQw1qbqZsPVhS6IpETIG+fvAGUliFA/JEY2JvNFrUt1AeqoS7KJWT4K+ov73gNItFYal5MjsF9jfIfc5apqhghlnnh0VVlgqTgsmb78yvuvK+7b9EScQWK6P8ZvARFo/TnFVq7xB9Oo8="
    - secure: "KMHKswaIbbsO9l2HG+LUn+lS1ixzw1T1exXTFNiPHucYbl3kmJjeeBZOKCCck2Vvr83T6KNkjMbNv9vap17jauHKOE5spN5zFXO5Gm1s7IUkOTv4ag6EqPt4hSL0FnRzYttX2fR+MXjjLzXwwlC3POBmMZbGkqGMDmVL0gR4+b8="
    - secure: "QrFIbtcWLAV/Z3Y4O/B33K3J6uUE4klLv6DMdlRIp0vlBR+VFoVF8Sax4PtY3Shl+tXOPfDJzcomBNFruEoIfImBe7rmL/NqWS0YEL9ZRJf8Q3bc+5vuJ6km6BV3rQh+N8gllMOOHJgXvnnadTDlez6BoOkliZAvNlnwO/u9prw="
    - secure: "Vd/IGXTddiLxRJvYHn/KOAVGwZA/MI4xG1MY8nMODQM0R/pf1/2z2cJCp03/vY1SReezdChv0uKz56SSbzNKAOrDht7fP7lXM7qkWUhOt4DKVt7SSEj8K88+chF2Es8T+wKgj0H++XaTCXNEVT95cDjlO+6RsN2V/RRTgUOXv1c="
    - secure: "kt9nrULPG9kLgJ4IYDmWUYmG1GifTrY3y7SY7TGOCoQOXp2tDIEd0ncoe0MnDOb6uqkowtAXHXW3scX03u6JuSbywno1JgtFiDYxIKolA9fyGAhowVneFiPn4JEkETaRNgJ0EqPZ5jvEVaAZqxFWqXP7gnbo4tSJjJiS3aBVzdo="
    - secure: "kIuJ/e6DOcNUVSnajmxgS666ivuX2BVRkav2LwHHgpeDg7Czi39nTQaQwBUoEd1EUW8IOF8VM7Qg3+gRcoKHFhg+JqmGFeMgyw6x3dMOZLiMBygPh3faac6KqLeNncARc7zFUh1q/7dY1E+YbiSrAoGVawKRMNbhVVQvUYkK2hY="
    - secure: "JSIJlBTBghnlCwU4U4gUY5AJ/1xK6uWayHmFOpnymwB7G5ff0CMqnfvHnkxBU5yQsoaMJTJYDiEQxrcrhSvciyAtkY1wJL7Ac67K4jdMHa3bnllL30sW181T80AArr+yCN+A7R5/MfLpJlwH4act/YZzKHVRIoFU6HQi4TVMTUU="
    - secure: "SKFfmcQ70BhtVG0icRh5jAkqIfz1KizrrLleMVzZ3p/1wv0CeWNveZHSrMLZM8gPts82F6MH61nOIqHDmGfl7i5roh9v3GNOFCfwS//h+Zk6Di1iV8lkwoNuJox3Ta0Xj7v4I8dh65wNweqazARrcUWwKKOChJoMDiajFVdlXIk="
    - secure: "bXtRPoyaLhlIYXEIAfqYSD0FW6n4GyxYsv9ZrBG3vquwG+tiFbJfAmN7fbROoy+AdxDH1YDUugDAVn9XGlcX7SuAd7KTLtj3MqmBMXG5eUEFMpUGGMWYaOBXMtcnXEQueOT6H5LVci3XzYvs+J3J9ThikEjwSU+FF/gyW9LQ7vk="
    - secure: "n2zkN73pN6a3/9lQMf77bji1b3nCVX+jXzzTAJ4Y0wq4JOGLPsvyjZZnu5KDyuNFd/77NpBKgupQY0fQyc7Ka7/KJKpHFA11B3PyxFsgVB8rrvgmrzPy855fUSJJpbXSveZN41QipfltKPvQNy53GcetnusOlhXhlX/W6r3AHZ4="
    - secure: "IRD+88HjgmF3p3fbC/VmqA9Rh22PRnjzcNhXZnlNjQArqEOUXmIUJt1ZpDdZy7xm0JCpJDUPYmn7YL+XQO7B5gNBQ6pmzJg4GVQ9hNcmJ4dpcTfxrs3Fm+JSRpnbWMacQEv5qO/8suGOM7BJ8m1+f2T2BfMtZ99X43pJffOw5Vw="
    - secure: "EAuo3XK2XwkWTZUe8EQKAgrL06MVy+eq5uVLxzwB10KnbFWOCwIDmmVI/stp7TO2MbIemWjgliJOya4/eHOlWDMK2XxMA3rRVEzXDD+KmfFkTq+HWbrzAhF75klLaUg9UIvjcMeKSMNDhlCeg1w4djYocVfAEuIZ4wo8Ak7NrcQ="
    - secure: "aXApDn8vLKLGlZA26+Go/HFdSoxWfBH1BvabV70cmuSQ8AOF3tFyee6RnfOoeOReMDyoWsKTrB693eOl4pa1nL2sL7r2iAPLlNQCsqqxhuPBip5y7yk5/gcVNM+OkfmS9f3PrFiSXN7pg+2kchO0MfgKzJxWb1+9dlnVghQNBAE="
    - secure: "HHyq7MznpHpkGgl0mCxfxnXo0mKZ2rEj59YBqX3Rzx4ycnRpMmK4sb0OT+wgo6EDOoWL3K85SfC/vkbDCpgzc+tRV7Ts+r1NvYNTB/y12Kn5MHG1L2Iua1Casj8114Nfygm8mt3A+LQ/4GUn9CyF0kJjOiAY1m7yrvSWqId+dmY="
    - secure: "Szult2vsgiECxBDC9lr4qhkkTWEv0Rett/8FgISqEaBFgtrTXWmkshJd6TxzqdbUhAgsZyHmKX2H43PWOQ8viwDomH2XgwBGtsToxllstQDMj3qwtb9dYEE+WtRss3hXHLl7Fcu4HDhR1iPdeg3FKMPOoGJdpp0kDD14VG1WTUg="
    - secure: "qD+De1wOEjvTTutt9Z2yTDbDUmUlK79ZBnRzq3QTMTxKBFGfi5ADkkpIiXRV+kbIb8HnpV+xHnWyhMI6gLHDs/u4kWDVDAjmvlpPmMoPhDqfEPYRqHZSmf0rYHd9UU/svKZSDCJjDYKScoYAmlNirtzVp9HQNhAZA9ZsyeWJne4="
    - secure: "eQo9D0MsEdxXDJjThfdMbEE5ZSWHyCZiNQvS0rtnKFIW3SZV3Baoen9eelyk0CHibHVQYK+p3YqJnEdFzBID92T/kV17XwClqHN3clF/3O88kSkAOZH+LtVOrsyAjXoNljASzD5W/EAaazruobQgyPm1mQE5pxk2VtVLFzYIk5Y="
    - secure: "mwM1vcWcMQnaE6dvSF35AafdeK0S+xveaCZnlxy9KY8GQpT/oIzbwsm8m72wX3tMqaTpsuKpm967N5ymeZz6A0g8Cf9L2mlfaUDDYwh1730EuxcowaGzWMn6J87VIcE0mSh/5PAFneboFkrTOqVjp7zVJaFyyR2sp3xy7cLQggE="
    - secure: "Y3T+sCBjYhR3u5j7DQadmf/pkygCk6UOSwkdJYxjQbN77KggzLnoCZU7uxRQ0QINQ1NTyUXKzmCMmaXa4IUUiDs7EnIQfo+6SWazUCqegTjTp5yZ5B5exxZIgP7Gut5HS9159ZkWYNIDyS54CpfOFAC9ZQ9osVCKGH+x/RkwTz8="
    - secure: "JjBEDglhKsiSF0jUIA9I3fJvMgTIVsPH7woSMtOR/wPyH9VpS0GcgV7o+peuaS6qpugkORbMeKUiO5ym+d+MNNBSINvsRZUsUQsIWX1FCeKqoRW13c4T9WtF3/rp9prTjEzVdu2bY2bNtM+YjfBrAbf89KOsGl8ESoLnouqqdXI="
    - secure: "DryJSJWKkPY3bfyvQmRD8IvRmjt4tzBhSR/FvVCH7KJow8Rk+zA55iZ2chl99IJXsdOhWL6b2bDnFbRJv90F6IPEw0ZCZSbSBWurbEloVIMIL9na6LWDptFw/Ddef+gjnTbuEJLCkMz66soKKEZsTL89GWtlKNXpHf6q1eYw6mM="
    - secure: "BkEllBAbvL10Wq20c9OWKKWqiWdXvZobhNnXo2wGbXgT99LrkjJbct2NHTVrwiFF2PVpnW2lGgaEH/eHq0s3c0anm1SKpAnw0/WVSPK4pcg/eHZznUe8pTFGxx4FzDCeur9Psrdy4QChqYUXNiAl64Np7YDA37uSHXjikOh+tgI="
    - secure: "sA2uongfDuch1WZJ0Cf0ffd2AIo0CnncuzXNPf9oWEUn+CFfM3mwejNGAYgobDNo3ClKb6xbKaD/Vz+xAiEf2sW11UgHTArayD15RLQPfS8vm5EQue479eD9IDjJowPnXOszZG03slorlAr7CYyW1t/6OmaIAoQeWtAxMyCCWug="
    - secure: "VemjdfeCcUb8X9lBIhb0n+3Z7RP/HQ9lKrHmBY+Klj+TPiSKe77se8NC927P/WEb4SF/ZoYCa9LruLhQ8KsX6puXnxAb95SZ7NRnVLxbiIfbNbAARSSOhuMYw8a3hG05Czq3N76G6xVzsahTqt14mgFYxIv4CtGnSQG1ovdtUDM="
    - secure: "dLAraFv8zJlqbheFSn5r4IXHxpBFx/EoSLLww7oX+lfsMmWncVEs/oyj+Wbic82kRKKR4y3E12UIIxxQh0SD7OzW0Ej3sn/gjIKVTc0xwurc+oqNJIqiZstSF7acIltqZ1nCausv1DLk769hzfZGkY3EHLTnKvp5lTa5yo0uqQw="
    - secure: "qNfTh7YehrsdeMtp/3GGqErM6xyyMVVtbApq/sDAy/MA/uJGcU9oboMFzqMYd8HEL5/yUtDb6Zj48qDJQroYHaX+LXmhd17NBWzAHrmQ1jMzDgsusaET8Od5uvEyKQaaaPrmo5yWo2g1djx90dn2S+KkzWQzc2otVWiSBF7GNqI="
    - secure: "XkV1PSwEeGhkGLl2MijbY7LSZuiVtmsUWltF+s6kNNzgcmwxYLHGGQNZOkkEqxNVkGmtf8Mty4xXYF8y6H2Fb4PkXgoezXAwqm/I49qTsTr2ru9C4Eo+c3zSoVjzIhMEYMj0VyzOzjthfNURC/qw3gO6lFgfgIasf9j1nuByCsE="
    - secure: "TBrP5hmZLnUxi+xMb8AFq39briaWuLCp+WWjGjPXy2ZUo93apvQMwNbT7rmo/Qq/rEFRVSDNn+JqiQPeIuJALcmzywTUGd+zrw5NOrL/NWttNwFXGGCdWy5Sr9+HW59m5A8aR2qTzJT7mxIvA47w8cpQEQeWCkbcBV8GoSC1TF8="
    - secure: "G6NKvXzabUlVafSjWrAu1hv6Y7Ew1UK9AWnsl9Db6Tco2mn9IzAn0xH/bX4yqOQHTNJTfL85UW0szJ1DFOdadvO6sFVvtKgNapMX6pqtqo2O4mRwYpktZJKFPUmDZndy8h8HVN8+wCQw+wlR6xex8UVg1GCyiNYaX5thpA3n8GU="
    - secure: "DbCxGosdunSKebxExTZbLJ+mbq5mfbFjIRA5YQDjht0NAI3VHD/L9FBpqyMOhFmT/5ZovseEv1F9EwnHVG6oU4RgEGeYEttb/qGtASsSFO3yZxbAhL33zM9LhJOTrRv0dN2TwzrXcmYxISZj/Q65hYdRV/heQPzcEugpPkibt6k="
    - secure: "bSRQuxNRYTtH4QhKYa4Yc6VP8rPyfYqLhFi//MgPHF1/uociaSf3zfYt/oRL/y/1jefXxgGrMLiKFDt24v6SaVjDgdldYOzoiE9gmVQyFarMqU+vVbLKlMyZnMUiweFgljZTG0OzlgTJ4899JlZuNpbxA9wNzidtEWLsHMSWNUg="
    - secure: "B7HFvICMhL5XxyQP4IjS3causFWlJhdfNGn5NmLL+3DhVfal4dplOQB+j4RVtVtvVUZBaCtzu0mXIhoepMuHrHQCO2VTuhMB+enC1Hlf+WtFBfYW0FQPpPHWizq2LNG/B27nEmhroMJ0LY9E6ufVkhAq6e/68DRUWIWmoKpISlI="
    - secure: "kHNl+zneX+pvJ+VgLsuKoQr3URMKm2zab+Mooz2/KnPCJ4XosGcx26eLVzbhAowu6ZjMfb7q15LzuSgATNH3T0UyNMTbHJjWNu2UdKqEci02+3iJOhIkdMtXBokqcMRiStOlL/mhKiHPROBqdEPy4ESa44H/HtLv6sKA1BTYum8="
    - secure: "GQB3VgXMHe1n+CbMpmzCaVWJi0LsU2MLfF+kq8ntfVkamrvztfSFg7avCr7/HAO+tZGqVTpeuOocZAzM/YlqVfr9B7WG9FTwVFZbJF4ighJ288asOQVGpyi1xl6vEpP1ZaYh3+5nwmlpG5Gmjaal4/j17Sj7yHgazSeji3yBDX8="
    - secure: "RTxP0UjyfebawXmt8ZwrzanEAgEN4JaITrcDB+dqyEOF7Hfu4/nun/aWTS37O2CRDqURyTmLTTtdg2Tgxkgfyg64fQU7RnMqAOhUl6vyX4P2ASgAleA7wgxusKtlfIhi0lZehyyPyp3E/jdTTw8FjlaEzeCCk0zFhS7f+FW58Pg="

branches:
  only:
    - master

notification:
  email:
    - zack9433@gmail.com
