sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - ~/.yarn
    - node_modules
env:
  global:
    - YARN_VERSION=1.3.2

before_install:
  - yarn global add greenkeeper-lockfile@1
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script: yarn build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

